In [ ]:
# C:\Users\spax2\Documents\PythonWork\農作業\vegetable_garden_photo_ex2.xlsxからデータを読み込みdfに入れる

In [1]:
import pandas as pd
import openpyxl
import datetime
from openpyxl import utils

from openpyxl import load_workbook
filepath= r"C:\Users\spax2\Documents\PythonWork\農作業\vegetable_garden_photo_ex2.xlsx"
wb=load_workbook(filename=filepath)
ws1=wb['vegetable_garden_photo']
ws2=wb['Selected_Data']

# データ表のリセット
wb.remove(wb['Selected_Data'])
s2=wb.create_sheet('Selected_Data')

df=pd.read_excel(filepath, sheet_name = "vegetable_garden_photo", index_col="Date")
df.reset_index(inplace=True)

df

,Date,Name or Item,Photo_id,JPG_Photo,Location,Tag1,Tag2,Tag3,Tag4,Tag5
0,2025-04-20,ジャガイモ,jR5zwRr87fxCDE899,20250420_111433836.JPG,北西,発芽開始,NaN,NaN,NaN,NaN
1,2025-04-20,ブロッコリー,nYf4iUqc7apcf1ub8,20250420_111441326.JPG,北中央,寒冷紗内で育成,NaN,NaN,NaN,NaN
2,2025-04-20,コウウン,QPyEx7kVykCXG9226,20250420_111450491.JPG,北東,耕運済,NaN,NaN,NaN,NaN
3,2025-04-20,タマネギ,ZH5WwPJRZtv5m7LA7,20250420_111455119.JPG,北東,手前は赤玉,中央と右端の黒マルチは普通の玉ねぎ,右端は冬季寒冷紗,NaN,NaN
4,2025-04-26,ズッキーニ,4zwmvagfWEcYq3iu9,20250426_160222550.JPG,南東,黒マルチ,種蒔き済,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
294,2025-11-26,タマネギ,EUvfFVTyuUFpKoCj9,20251126_100052304.JPG,中央北,赤玉苗,NaN,NaN,NaN,NaN
295,2025-11-26,ネギ,ppjN71BS38jBYFVm9,20251126_100430148.JPG,南東,施肥 ネギタマネギ専用,NaN,NaN,NaN,NaN
296,2025-11-26,ネギ,2kBe7Ph19YL3kgd27,20251126_101228315.JPG,南東,稲原敷き込み,NaN,NaN,NaN,NaN
297,2025-11-26,ネギ,FLUnGG5dy5gx34sg7,20251126_102441017.JPG,南東,施肥 ネギタマネギ専用,土寄せ,NaN,NaN,NaN
298,2025-11-26,ネギ,1GPFxi8czpPaNT4w5,20251126_102449449.JPG,南東,土寄せ,NaN,NaN,NaN,NaN

In [3]:
import datetime as dt 
import date_input_module 

df['Date'] = pd.to_datetime(df['Date']).dt.date

print("開始日") 
idt_start = date_input_module.validate_date(date_input_module.input_date())
print(idt_start)
print("終了日")
idt_end = date_input_module.validate_date(date_input_module.input_date())
print(idt_end)

#DataFrame fdから指定された期間のデータを抜き出しfd2を作る

if idt_start and idt_end:
    df2 = df[(df['Date'] >= idt_start) & (df['Date'] <= idt_end)]
else:
    print("日付の入力に問題がありました。")

df2

開始日
2025-03-01
終了日
2025-10-10

,Date,Name or Item,Photo_id,JPG_Photo,Location,Tag1,Tag2,Tag3,Tag4,Tag5
0,2025-04-20,ジャガイモ,jR5zwRr87fxCDE899,20250420_111433836.JPG,北西,発芽開始,NaN,NaN,NaN,NaN
1,2025-04-20,ブロッコリー,nYf4iUqc7apcf1ub8,20250420_111441326.JPG,北中央,寒冷紗内で育成,NaN,NaN,NaN,NaN
2,2025-04-20,コウウン,QPyEx7kVykCXG9226,20250420_111450491.JPG,北東,耕運済,NaN,NaN,NaN,NaN
3,2025-04-20,タマネギ,ZH5WwPJRZtv5m7LA7,20250420_111455119.JPG,北東,手前は赤玉,中央と右端の黒マルチは普通の玉ねぎ,右端は冬季寒冷紗,NaN,NaN
4,2025-04-26,ズッキーニ,4zwmvagfWEcYq3iu9,20250426_160222550.JPG,南東,黒マルチ,種蒔き済,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
230,2025-10-07,コマツナ,ZUNBwRLG2JBAspFc8,20251007_145455237.JPG,北東,発芽,NaN,NaN,NaN,NaN
231,2025-10-07,ミズナ,NduxY2FspcftEPym8,20251007_145503070.JPG,北東,発芽,NaN,NaN,NaN,NaN
232,2025-10-07,チンゲンサイ,q1RDbZL1PzYGSfEu5,20251007_145516360.JPG,北東,発芽,NaN,NaN,NaN,NaN
233,2025-10-07,ホウレンソウ,RMzjZwvpFzH6HJ3MA,20251007_145522962.JPG,北東,発芽,NaN,NaN,NaN,NaN
234,2025-10-07,ネギ,eMX2Jf3vgGqpd3Ey9,20251007_153304453.JPG,南東,定植,100本,NaN,NaN,NaN

In [4]:
import date_input_module
import pandas as pd

# 日付入力
print("開始日を入力してください")
start_date = date_input_module.validate_date(date_input_module.input_date())
print(start_date)
print("終了日を入力してください")
end_date = date_input_module.validate_date(date_input_module.input_date())
print(end_date)

# 品名入力
item_name = input("品名（Name or Item）を入力してください(カタカナ)：").strip()

# --- ここがポイント：DataFrame側を datetime64[ns] に統一 ---
df['Date'] = pd.to_datetime(df['Date'])        # .dt.date は付けない

# 入力側も Timestamp に
start_ts = pd.to_datetime(start_date)
end_ts   = pd.to_datetime(end_date)

# 抽出
if pd.notna(start_ts) and pd.notna(end_ts) and item_name:
    df2 = df[
        (df['Date'] >= start_ts) &
        (df['Date'] <= end_ts) &
        (df['Name or Item'] == item_name)
    ]
else:
    print("入力に問題がありました。")

df2

開始日を入力してください
2025-03-10
終了日を入力してください
2025-10-10

,Date,Name or Item,Photo_id,JPG_Photo,Location,Tag1,Tag2,Tag3,Tag4,Tag5
3,2025-04-20,タマネギ,ZH5WwPJRZtv5m7LA7,20250420_111455119.JPG,北東,手前は赤玉,中央と右端の黒マルチは普通の玉ねぎ,右端は冬季寒冷紗,NaN,NaN
25,2025-05-01,タマネギ,wRscSWWRQ99BPqu47,20250501_113844875.JPG,北東,黒マルチ,生育中,寒冷紗は外した,NaN,NaN
71,2025-06-06,タマネギ,FutoPp7o7ppJfYCb9,20250608_122805959.JPG,北東,収穫,NaN,NaN,NaN,NaN
101,2025-06-29,タマネギ,rqm2ZQ1vDXwJt3tF7,20250629_110755386.JPG,北東,収穫後,耕運,NaN,NaN,NaN
198,2025-09-26,タマネギ,LZzVrf1xoqrWA8b5A,20250926_125027073.JPG,北中央,赤玉,種蒔き,寒冷紗,NaN,NaN
199,2025-09-26,タマネギ,6o5PRWXca8DnnuDm8,20250926_154559298.JPG,北中央,タマネギ,種蒔き,寒冷紗,NaN,NaN
219,2025-10-03,タマネギ,ng53SnQTzA34aFzv7,20251003_091324315.JPG,北中央,赤玉,発芽,不織布,NaN,NaN

In [6]:

df2

,Date,Name or Item,Photo_id,JPG_Photo,Location,Tag1,Tag2,Tag3,Tag4,Tag5
3,2025-04-20,タマネギ,ZH5WwPJRZtv5m7LA7,20250420_111455119.JPG,北東,手前は赤玉,中央と右端の黒マルチは普通の玉ねぎ,右端は冬季寒冷紗,NaN,NaN
25,2025-05-01,タマネギ,wRscSWWRQ99BPqu47,20250501_113844875.JPG,北東,黒マルチ,生育中,寒冷紗は外した,NaN,NaN
71,2025-06-06,タマネギ,FutoPp7o7ppJfYCb9,20250608_122805959.JPG,北東,収穫,NaN,NaN,NaN,NaN
101,2025-06-29,タマネギ,rqm2ZQ1vDXwJt3tF7,20250629_110755386.JPG,北東,収穫後,耕運,NaN,NaN,NaN
198,2025-09-26,タマネギ,LZzVrf1xoqrWA8b5A,20250926_125027073.JPG,北中央,赤玉,種蒔き,寒冷紗,NaN,NaN
199,2025-09-26,タマネギ,6o5PRWXca8DnnuDm8,20250926_154559298.JPG,北中央,タマネギ,種蒔き,寒冷紗,NaN,NaN
219,2025-10-03,タマネギ,ng53SnQTzA34aFzv7,20251003_091324315.JPG,北中央,赤玉,発芽,不織布,NaN,NaN

In [5]:
# 選択されたdf2のPhoto_idにhttps://photos.app.goo.gl/
# を付け加えchromeに表示する

df3 = df2.copy()
df3['Photo_url'] = "https://photos.app.goo.gl/" + df3['Photo_id']

import webbrowser

chrome_path = 'C:/Program Files/Google/Chrome/Application/chrome.exe'
webbrowser.register('chrome', None, webbrowser.BackgroundBrowser(chrome_path))
browser = webbrowser.get('chrome')

for url in df3['Photo_url']:
    browser.open(url)

In [ ]:
from IPython.display import Image, display
import os

image_folder = r"G:\その他のパソコン\マイ ノートパソコン\Pictures\Vegetables"
shown_images = set()  # 表示済み画像の記録

#print(df2)

for _, row in df2.iterrows():
    print(f"📅 日付: {row['Date']}")
    
    image_path = os.path.join(image_folder, row['JPG_Photo'])
    if row['JPG_Photo'] not in shown_images and os.path.exists(image_path):
        display(Image(filename=image_path, width=400))  # 写真を表示
        shown_images.add(row['JPG_Photo'])
    else:
        print("（写真は省略）")
    
    # その他の情報を表示
    print(f"🥬 品名: {row['Name or Item']}")
    print(f"📍 場所: {row['Location']}")
    print(f"🏷️ タグ: {row['Tag1']}, {row['Tag2']}, {row['Tag3']}, {row['Tag4']}, {row['Tag5']}")
    print("-" * 40)

In [8]:
!streamlit run C:\Users\spax2\Documents\PythonWork\農作業\start_page.py

^C